### ISSUE TITLE
[Landing page] Implement styleguide in theme

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-homepage#11]
## What is this feature about

The [styleguide](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?node-id=22%3A48&t=EfbQ76DQgEiS3stl-0) is not centralised in the theme.

## The list of requirements

The following needs to be added to the theme and the pages updated accordingly:

- [ ] Typography
- [ ] Colors
- [ ] Buttons

## Designs/sketches

- [Spec](https://www.notion.so/gnosis-safe/Progress-and-Content-Blocks-981ce5aea1a54d89b5b93a4aa9e5b289)
- [Figma](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?node-id=22%3A48&t=EfbQ76DQgEiS3stl-0)
- [Overview](https://www.notion.so/gnosis-safe/Landing-Page-352ef9f0174e4738aa531863d355c54d)
- [Timeline](https://www.notion.so/gnosis-safe/Landing-page-33a1b30441614574971718ce66d285ec)

**Comment by DiogoSoaress** [comment]
Styleguides have been implemented in the theme.
