### ISSUE TITLE
Support the use of trailing slash

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-homepage#171]
CLA scripts in all the Safe repositories point to `https://safe.global/cla/` (see https://github.com/safe-global/safe-homepage/blob/main/.github/workflows/cla.yml#L23 as an example).

https://safe.global/cla shows the right page, but https://safe.global/cla/ doesn't.
The same issue happens with all the other pages like `/core`, `/wallet`, etc.

Supporting the addition of a trailing slash would fix this issue.

**Comment by katspaugh** [comment]
This can be probably fixed by adding a `pages/cla` folder with a symlink to `cla.tsx` inside.

**Comment by katspaugh** [comment]
Fixed in #172.

**Comment by tolbrino** [comment]
Still not working. `/cla` works but `/cla/` does not.
