### ISSUE TITLE
[Ecosystem page] Create a request template for adding new Safe projects

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-homepage#179]
Note: [JSON DB repo](https://github.com/safe-global/safe-homepage/issues/175) needs to be created first.

## What is the feature about

Creating a GitHub issue to submit a new project to the ecosystem page

## The list of requirements

1. Create and add issue template to [repo hosting the JSON DB of projects](https://github.com/safe-global/safe-homepage/issues/175).

## Links

- [Epic](https://github.com/safe-global/safe-homepage/issues/161).
- [Example issue templates](https://github.com/safe-global/safe-homepage/issues/161#issuecomment-1481224881).

**Comment by usame-algan** [comment]
Can be tested here: https://github.com/safe-global/safe-ecosystem-database/issues/new/choose
