### ISSUE TITLE
Prevent trailing slashes from resulting in 404

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-homepage#183]
If a URL has a trailing slash, it will result in a 404, e.g. [this](https://safe.global/cla/). This was fixed in [`web-core` directly](https://github.com/safe-global/web-core/pull/1907) but we should prevent this from happening in the homepage itself.

**Comment by usame-algan** [comment]
A bit more discussion on this topic: [Slack](https://5afe.slack.com/archives/C049H57FS1E/p1686069103973699)

By default, Nextjs supports both but our server config doesn't rewrite trailing slashes so it needs to be fixed there.
