### ISSUE TITLE
[UI improvement] Header update

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-homepage#250]
The header needs a few small UI updates. It currently pushes the content a bit too low. Therefore, I propose the following:
- New height on web (1440px): `72px` (it will reduce the height by ~20px)
- Height on mobile (375px): 64px 
- When scrolling: underline stroke 1px, 0.1 opacity
- Background blur: 16px

See [reference for component in Figma](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?type=design&node-id=6456%3A16069&mode=design&t=tqpRGfyBaxsCO5Nx-1)

**Comment by DiogoSoaress** [comment]
@TanyaEfremova can you update the Header design to contain the Safe{CON} button?

Should we also rethink having removed the Careers button? You  shared some interesting stats in https://5afe.slack.com/archives/C04LENM73JQ/p1709211448334029?thread_ts=1709136666.405599&cid=C04LENM73JQ but I also feel it is not very common to have such button in the Header but rather in the Footer.

**Comment by TanyaEfremova** [comment]
I updated the layout in [Figma](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?type=design&node-id=22%3A48&mode=design&t=y8rhuSuu1GKKOitZ-1) and removed the button to careers page. It does draw quite some attention, hence the stats. 

I would suggest to also include a counter tag in the footer, as it used to be in the main nav.
