### ISSUE TITLE
Background behind icon

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-homepage#293]
On the governance page, there is a black background behind the arrow icon above the "Who are Safe{Guardians}" section that looks like it should not be there:

![image](https://github.com/safe-global/safe-homepage/assets/20442784/d21ec5b5-dedc-44d2-b770-974f8b57521e)

**Comment by DiogoSoaress** [comment]
@TanyaEfremova can you provide this icon without that background around the arrow?

**Comment by TanyaEfremova** [comment]
Heere is the fixed icon: 
![Safe_Icons_Secure_Black](https://github.com/safe-global/safe-homepage/assets/93707525/2f40dcb4-26f2-4f17-84bc-74a69a22ed3b)
