### ISSUE TITLE
[Safe{Pass}] Add hero section and partners section

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-homepage#336]
1. Add a hero section with H1 title and a tag above the pass visual. [
2. Add partners logos below the pass visual. 

[See design](https://www.figma.com/file/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?type=design&node-id=11576%3A4093&mode=design&t=t709Hr5IvwAYyCSt-1)

For the responsive version, see [reference](https://www.figma.com/file/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?type=design&node-id=12889%3A10266&mode=design&t=t709Hr5IvwAYyCSt-1)

**Comment by DiogoSoaress** [comment]
Implemented in https://github.com/safe-global/safe-homepage/pull/337
