### ISSUE TITLE
New feature banner is stretched incorrectly

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-homepage#356]
### Description
There is a bug with the banner on the [Wallet page](https://safe.global/wallet), around 1700px breakpoint it stretches across the page, and then it is shown correctly again with the margins on the sides.
See screenshots below.

### Expected result
The banner should preserve margins on all breakpoints.
<img width="1041" alt="Screenshot 2024-05-27 at 16 56 18" src="https://github.com/safe-global/safe-homepage/assets/93707525/a3164c44-0f01-4b38-ad35-c5f06aaf4b58">
<img width="1053" alt="Screenshot 2024-05-27 at 16 56 30" src="https://github.com/safe-global/safe-homepage/assets/93707525/3e160b71-de83-4428-a07a-43c687f8777d">

**Comment by DiogoSoaress** [comment]
Replaced by #404
